const actionTypes = {
  SET_NOTES: "SET_NOTES",
  SET_ARCHIVED: "SET_ARCHIVED",
  SET_TRASH: "SET_TRASH",
  SET_NOTES_AND_ARCHIVE: "SET_NOTES_AND_ARCHIVE",
  SET_NOTES_AND_TRASH: "SET_NOTES_AND_TRASH",
  SET_ARCHIVE_AND_TRASH: "SET_ARCHIVE_AND_TRASH",
};

export { actionTypes };
